extensionsToFolder = {
    ".pdf": "k-DOCUMENTS",
    ".doc": "k-DOCUMENTS",
    ".docx": "k-DOCUMENTS",
    ".txt": "k-DOCUMENTS",
    ".ppt": "k-DOCUMENTS",
    ".pptx": "k-DOCUMENTS",
    ".xls": "k-DOCUMENTS",
    ".xlsx": "k-DOCUMENTS",
    ".mp4": "k-VIDEOS",
    ".avi": "k-VIDEOS",
    ".mkv": "k-VIDEOS",
    ".webm": "k-VIDEOS",
    ".flv": "k-VIDEOS",
    ".mov": "k-VIDEOS",
    ".mp3": "k-AUDIO",
    ".wav": "k-AUDIO",
    ".aac": "k-AUDIO",
    ".wma": "k-AUDIO",
    ".m4a": "k-AUDIO",
    ".flac": "k-AUDIO",
    ".jpeg": "k-IMAGES",
    ".jpg": "k-IMAGES",
    ".png": "k-IMAGES",
    ".gif": "k-IMAGES",
    ".tiff": "k-IMAGES",
    ".raw": "k-IMAGES"
}
